import type { Category, Product } from "./types";

const tiered = (
  retail: number,
  tier1: number,
  tier2: number,
): Product["priceTiers"] => [
  { minQty: 6, maxQty: 11, unitPrice: tier1, label: "Wholesale tier 1 (6–11 pcs)" },
  { minQty: 12, maxQty: null, unitPrice: tier2, label: "Wholesale tier 2 (12+ pcs)" },
];

export const products: Product[] = [
  {
    id: "p-classic-black",
    slug: "jg-classic-black",
    sku: "JG-CLS-BLK-01",
    name: "JG Classic Black",
    shortDescription:
      "Timeless square frame in matte acetate — the everyday staple.",
    description:
      "The JG Classic Black is a clean, modern square frame crafted from premium Italian acetate. Spring-hinged temples, lightweight construction, and a versatile silhouette make it the perfect daily eyewear for work, study, or a casual evening out.",
    category: "eyeglasses",
    categoryLabel: "Eyeglasses",
    gender: "unisex",
    style: "casual",
    frame: "rectangle",
    retailPrice: 145000,
    resellerPrice: 105000,
    priceTiers: tiered(145000, 125000, 110000),
    minWholesaleQty: 6,
    stock: 84,
    weightGram: 60,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    rating: 4.8,
    reviewCount: 132,
    colors: ["#01083c", "#1a225a"],
    frameColor: "black",
    lensColor: "clear",
    specs: [
      { label: "Frame Material", value: "Italian acetate" },
      { label: "Hinge", value: "Spring-hinge" },
      { label: "Lens Width", value: "52 mm" },
      { label: "Bridge", value: "20 mm" },
      { label: "Temple", value: "145 mm" },
    ],
    variants: [],
  },
  {
    id: "p-round-gold",
    slug: "jg-round-gold",
    sku: "JG-RND-GLD-01",
    name: "JG Round Gold",
    shortDescription: "Vintage-inspired round wire frame in brushed gold.",
    description:
      "A modern take on the heritage round frame — slim brushed-gold metal, adjustable nose pads, and ultra-light wire temples that feel barely-there. Effortless, refined, and conversation-starting.",
    category: "eyeglasses",
    categoryLabel: "Eyeglasses",
    gender: "unisex",
    style: "vintage",
    frame: "round",
    retailPrice: 165000,
    resellerPrice: 119000,
    priceTiers: tiered(165000, 142000, 125000),
    minWholesaleQty: 6,
    stock: 56,
    weightGram: 45,
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: true,
    rating: 4.7,
    reviewCount: 88,
    colors: ["#1a225a", "#2a3470"],
    frameColor: "gold",
    lensColor: "clear",
    specs: [
      { label: "Frame Material", value: "Brushed metal" },
      { label: "Hinge", value: "Standard" },
      { label: "Lens Width", value: "49 mm" },
      { label: "Bridge", value: "21 mm" },
      { label: "Temple", value: "145 mm" },
    ],
    variants: [],
  },
  {
    id: "p-aviator-elite",
    slug: "jg-aviator-elite",
    sku: "JG-AVT-ELT-01",
    name: "JG Aviator Elite",
    shortDescription: "Polarized aviator sunglasses with smoked green lenses.",
    description:
      "Iconic teardrop silhouette, hand-finished metal frame, and polarized green-smoke lenses with full UV400 protection. Lightweight comfort meets serious sun-defense for highway drives, beach days, and rooftop evenings.",
    category: "sunglasses",
    categoryLabel: "Sunglasses",
    gender: "men",
    style: "premium",
    frame: "aviator",
    retailPrice: 185000,
    resellerPrice: 135000,
    priceTiers: tiered(185000, 162000, 145000),
    minWholesaleQty: 6,
    stock: 42,
    weightGram: 55,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    rating: 4.9,
    reviewCount: 214,
    colors: ["#01083c", "#2a6df0"],
    frameColor: "black",
    lensColor: "green",
    specs: [
      { label: "Lens Type", value: "Polarized, UV400" },
      { label: "Frame Material", value: "Aviation-grade metal" },
      { label: "Lens Width", value: "58 mm" },
      { label: "Bridge", value: "14 mm" },
      { label: "Temple", value: "140 mm" },
    ],
    variants: [],
  },
  {
    id: "p-tortoise-brown",
    slug: "jg-tortoise-brown",
    sku: "JG-TRT-BRN-01",
    name: "JG Tortoise Brown",
    shortDescription:
      "Classic browline frame in rich tortoise acetate — bookish charm.",
    description:
      "A sophisticated browline frame with hand-polished tortoise pattern and slim metal accents. Rounded corners and a slightly curved brow give a soft, intelligent character that flatters most face shapes.",
    category: "eyeglasses",
    categoryLabel: "Eyeglasses",
    gender: "unisex",
    style: "fashion",
    frame: "browline",
    retailPrice: 155000,
    resellerPrice: 112000,
    priceTiers: tiered(155000, 134000, 119000),
    minWholesaleQty: 6,
    stock: 71,
    weightGram: 58,
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: true,
    rating: 4.6,
    reviewCount: 95,
    colors: ["#060c3f", "#1a225a"],
    frameColor: "tortoise",
    lensColor: "clear",
    specs: [
      { label: "Frame Material", value: "Acetate + metal brow" },
      { label: "Hinge", value: "Spring-hinge" },
      { label: "Lens Width", value: "51 mm" },
      { label: "Bridge", value: "21 mm" },
      { label: "Temple", value: "145 mm" },
    ],
    variants: [],
  },
  {
    id: "p-bluelight-pro",
    slug: "jg-bluelight-pro",
    sku: "JG-BLP-NVY-01",
    name: "JG Bluelight Pro",
    shortDescription: "Anti-blue-light lenses for long screen days.",
    description:
      "Designed for developers, designers, and anyone who lives on-screen. The Bluelight Pro filters up to 40% of high-energy blue light while keeping colors true. Ultra-light TR-90 frame stays comfortable through 12-hour shifts.",
    category: "blue-light",
    categoryLabel: "Blue Light Glasses",
    gender: "unisex",
    style: "casual",
    frame: "rectangle",
    retailPrice: 175000,
    promotionalPrice: 149000,
    resellerPrice: 122000,
    priceTiers: tiered(175000, 149000, 132000),
    minWholesaleQty: 6,
    stock: 120,
    weightGram: 25,
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: true,
    rating: 4.7,
    reviewCount: 168,
    colors: ["#01083c", "#2a6df0"],
    frameColor: "navy",
    lensColor: "amber",
    specs: [
      { label: "Frame Material", value: "TR-90 thermoplastic" },
      { label: "Lens Filter", value: "Up to 40% HEV blue light" },
      { label: "Lens Width", value: "53 mm" },
      { label: "Bridge", value: "18 mm" },
      { label: "Temple", value: "145 mm" },
    ],
    variants: [],
  },
  {
    id: "p-cateye-rose",
    slug: "jg-cateye-rose",
    sku: "JG-CAT-RSE-01",
    name: "JG Cat Eye Rose",
    shortDescription: "Sculpted cat-eye in rose-tinted acetate.",
    description:
      "A confident silhouette with sculpted brow corners and a soft rose translucent finish. Built for everyday glamour — from morning meetings to weekend brunches.",
    category: "eyeglasses",
    categoryLabel: "Eyeglasses",
    gender: "women",
    style: "fashion",
    frame: "cateye",
    retailPrice: 169000,
    resellerPrice: 122000,
    priceTiers: tiered(169000, 145000, 129000),
    minWholesaleQty: 6,
    stock: 38,
    weightGram: 50,
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true,
    rating: 4.6,
    reviewCount: 47,
    colors: ["#7cabff", "#1a225a"],
    frameColor: "rose",
    lensColor: "clear",
    specs: [
      { label: "Frame Material", value: "Italian acetate" },
      { label: "Lens Width", value: "52 mm" },
      { label: "Bridge", value: "18 mm" },
      { label: "Temple", value: "140 mm" },
    ],
    variants: [],
  },
  {
    id: "p-sport-runner",
    slug: "jg-sport-runner",
    sku: "JG-SPR-OLV-01",
    name: "JG Sport Runner",
    shortDescription: "Wraparound sport sunglasses for active days.",
    description:
      "Aerodynamic wraparound sport sunglasses with grippy nose pads, anti-fog vents, and shatter-resistant polycarbonate lenses. Built for runners, cyclists, and weekend warriors.",
    category: "sunglasses",
    categoryLabel: "Sunglasses",
    gender: "unisex",
    style: "sport",
    frame: "rectangle",
    retailPrice: 159000,
    resellerPrice: 115000,
    priceTiers: tiered(159000, 138000, 122000),
    minWholesaleQty: 6,
    stock: 64,
    weightGram: 30,
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: false,
    rating: 4.5,
    reviewCount: 73,
    colors: ["#2a3470", "#01083c"],
    frameColor: "olive",
    lensColor: "smoke",
    specs: [
      { label: "Frame Material", value: "Polycarbonate" },
      { label: "Lens Type", value: "UV400, anti-scratch" },
      { label: "Lens Width", value: "62 mm" },
      { label: "Bridge", value: "12 mm" },
      { label: "Temple", value: "135 mm" },
    ],
    variants: [],
  },
  {
    id: "p-mirror-silver",
    slug: "jg-mirror-silver",
    sku: "JG-MIR-SLV-01",
    name: "JG Mirror Silver",
    shortDescription: "Statement aviators with silver mirror lenses.",
    description:
      "Bold reflective aviators with a polished silver finish and double-bridge construction. UV400 protection wrapped in unmistakable confidence.",
    category: "sunglasses",
    categoryLabel: "Sunglasses",
    gender: "unisex",
    style: "fashion",
    frame: "aviator",
    retailPrice: 199000,
    resellerPrice: 145000,
    priceTiers: tiered(199000, 172000, 155000),
    minWholesaleQty: 6,
    stock: 28,
    weightGram: 53,
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true,
    rating: 4.8,
    reviewCount: 36,
    colors: ["#aab2cf", "#495489"],
    frameColor: "silver",
    lensColor: "mirror",
    specs: [
      { label: "Lens Type", value: "Mirror coated, UV400" },
      { label: "Frame Material", value: "Stainless steel" },
      { label: "Lens Width", value: "60 mm" },
      { label: "Bridge", value: "14 mm" },
      { label: "Temple", value: "140 mm" },
    ],
    variants: [],
  },
  {
    id: "p-kid-buddy",
    slug: "jg-kid-buddy",
    sku: "JG-KID-NVY-01",
    name: "JG Kid Buddy",
    shortDescription: "Flexible blue-light glasses for kids 6–12.",
    description:
      "Bend-don't-break TR-90 frames with soft silicone temple tips and 35% blue-light filtering — perfect for tablet time, online classes, and screen-heavy school days.",
    category: "blue-light",
    categoryLabel: "Blue Light Glasses",
    gender: "kids",
    style: "casual",
    frame: "round",
    retailPrice: 125000,
    resellerPrice: 89000,
    priceTiers: tiered(125000, 108000, 95000),
    minWholesaleQty: 6,
    stock: 92,
    weightGram: 18,
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: false,
    rating: 4.7,
    reviewCount: 51,
    colors: ["#1a225a", "#7cabff"],
    frameColor: "navy",
    lensColor: "amber",
    specs: [
      { label: "Frame Material", value: "TR-90 thermoplastic" },
      { label: "Recommended Age", value: "6–12 years" },
      { label: "Lens Width", value: "44 mm" },
      { label: "Bridge", value: "16 mm" },
      { label: "Temple", value: "120 mm" },
    ],
    variants: [],
  },
  {
    id: "p-premium-titanium",
    slug: "jg-premium-titanium",
    sku: "JG-PRM-TIT-01",
    name: "JG Premium Titanium",
    shortDescription: "Featherweight titanium frame — uncompromising luxury.",
    description:
      "Hand-finished beta-titanium frame with hypoallergenic nose pads and Japanese hinges. Weighs less than 14g, yet feels engineered for a lifetime of daily wear.",
    category: "eyeglasses",
    categoryLabel: "Eyeglasses",
    gender: "men",
    style: "premium",
    frame: "rectangle",
    retailPrice: 285000,
    resellerPrice: 215000,
    priceTiers: tiered(285000, 248000, 225000),
    minWholesaleQty: 6,
    stock: 22,
    weightGram: 14,
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true,
    rating: 4.9,
    reviewCount: 41,
    colors: ["#1a225a", "#01083c"],
    frameColor: "silver",
    lensColor: "clear",
    specs: [
      { label: "Frame Material", value: "Beta-titanium" },
      { label: "Hinge", value: "Japanese spring-hinge" },
      { label: "Lens Width", value: "54 mm" },
      { label: "Bridge", value: "18 mm" },
      { label: "Temple", value: "145 mm" },
    ],
    variants: [],
  },
  {
    id: "p-case-leather",
    slug: "jg-leather-case",
    sku: "JG-ACC-CSE-01",
    name: "JG Hard Leather Case",
    shortDescription:
      "Premium hard-shell case with magnetic closure and microfiber lining.",
    description:
      "A protective hard-shell eyewear case wrapped in vegan leather, lined with soft microfiber, and finished with a satisfying magnetic snap closure. Fits all JG eyewear sizes.",
    category: "accessories",
    categoryLabel: "Accessories",
    gender: "unisex",
    style: "premium",
    frame: "rectangle",
    retailPrice: 65000,
    resellerPrice: 42000,
    priceTiers: tiered(65000, 55000, 48000),
    minWholesaleQty: 6,
    stock: 240,
    weightGram: 90,
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: false,
    rating: 4.8,
    reviewCount: 312,
    colors: ["#01083c", "#2a3470"],
    frameColor: "black",
    specs: [
      { label: "Material", value: "Vegan leather, hard shell" },
      { label: "Closure", value: "Magnetic snap" },
      { label: "Includes", value: "Microfiber cleaning cloth" },
    ],
    variants: [],
  },
  {
    id: "p-cleaning-kit",
    slug: "jg-cleaning-kit",
    sku: "JG-ACC-CLN-01",
    name: "JG Lens Cleaning Kit",
    shortDescription:
      "Spray + microfiber cloth bundle for streak-free clarity.",
    description:
      "Alcohol-free anti-smudge cleaning spray paired with two premium microfiber cloths. Safe for anti-reflective and blue-light coated lenses.",
    category: "accessories",
    categoryLabel: "Accessories",
    gender: "unisex",
    style: "casual",
    frame: "rectangle",
    retailPrice: 35000,
    resellerPrice: 22000,
    priceTiers: tiered(35000, 30000, 26000),
    minWholesaleQty: 6,
    stock: 410,
    weightGram: 80,
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: false,
    rating: 4.6,
    reviewCount: 218,
    colors: ["#aab2cf"],
    frameColor: "silver",
    specs: [
      { label: "Includes", value: "30ml spray + 2 microfiber cloths" },
      { label: "Coatings", value: "Safe for AR, BL, and mirror lenses" },
    ],
    variants: [],
  },
];

export const categories: Category[] = [
  {
    slug: "eyeglasses",
    name: "Eyeglasses",
    description:
      "Everyday optical frames crafted from acetate, titanium, and TR-90.",
    productCount: products.filter((p) => p.category === "eyeglasses").length,
  },
  {
    slug: "sunglasses",
    name: "Sunglasses",
    description: "UV400-protected fashion and sport sunglasses.",
    productCount: products.filter((p) => p.category === "sunglasses").length,
  },
  {
    slug: "blue-light",
    name: "Blue Light Glasses",
    description: "Anti-blue-light lenses for long screen days.",
    productCount: products.filter((p) => p.category === "blue-light").length,
  },
  {
    slug: "accessories",
    name: "Accessories",
    description: "Cases, cleaning kits, and care essentials.",
    productCount: products.filter((p) => p.category === "accessories").length,
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category);
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return products
    .filter((p) => p.id !== product.id && p.category === product.category)
    .slice(0, limit);
}
